### PR TITLE
Add a probe for outgoing requests with Faraday

### PR DESCRIPTION
**Pull request by franzliedke**
I would like to use this to gain more insight into strange behavior on our production platform.

### CODE REVIEW

**Comment by franzliedke** [comment]
Is there any other meta information we want to add to the trace (currently, we track `method`, `url` and `status`).

**Comment by franzliedke** [comment]
Rebased to fix the conflicts.

**Comment by jgraichen** [comment]
Thanks. I'm still waiting to see if everything on master passes now.

**Comment by jgraichen** [comment]
@franzliedke Can you do another rebase on the green master?

**Comment by franzliedke** [comment]
I just released v1.6.2. with [a fix](https://github.com/mnemosyne-mon/mnemosyne-ruby/commit/d1d92d66e7bc4b0bc21b0a33eadf3787b4d9a3d2) for requests with bodies.

**Pull request merged**
