### PR TITLE
Instrument view_component gem

### PR DESCRIPTION
**Pull request by franzliedke**
We're considering switching to this library for performance reasons. It
is well maintained and has built-in instrumentation support using
ActiveSupport, so this was easy.

Tested locally in our main app.

### CODE REVIEW

**Review by Dome-GER — APPROVED** [review]
Looks good.

I was wondering about the event name with the `!` for a second but it's correct. 😲

**Comment by jgraichen** [comment]
Would you like to add some specs?

**Comment by franzliedke** [comment]
> I was wondering about the event name with the ! for a second but it's correct.

Ha, that caught me, too. No idea whether there is some convention behind it (e.g. third-party stuff vs. Rails core?).

**Comment by franzliedke** [comment]
> Would you like to add some specs?

What scenario would you like to see tested? There wasn't a dummy Rails app in the tests here yet, so I decided against it. 😕 I did examine the output very carefully, locally.

**Comment by franzliedke** [comment]
@jgraichen Please let me know what you'd like to see tested.

**Comment by jgraichen** [comment]
Something similar to [spec/mnemosyne/probes/active_job/perform_spec.rb](https://github.com/mnemosyne-mon/mnemosyne-ruby/blob/a4b8e075adfe8b2bbf60d4009c78c2ae55b0ee57/spec/mnemosyne/probes/active_job/perform_spec.rb) or [spec/mnemosyne/probes/active_record/query_spec.rb](https://github.com/mnemosyne-mon/mnemosyne-ruby/blob/a4b8e075adfe8b2bbf60d4009c78c2ae55b0ee57/spec/mnemosyne/probes/active_record/query_spec.rb), a minimal rendering of a component to trigger the event.

Actually, if you say that isn't worth the effort, I am fine with not testing it here.

**Review by jgraichen — APPROVED** [review]

**Pull request merged**
